title: pwa
description: A course about Progressive Web Apps.
template:
  repo: pwa-template
  name: my-awesome-pwa-course
before:
  - type: octokit
    method: issues.createMilestone
    owner: "%payload.repository.owner.login%"
    repo: "%payload.repository.name%"
    title: Modul 0
    description: Introduktion till kursen
  - type: createIssue
    title: Modul 0 - Hello World
    body: module-0/module-0-lesson-1.md
  - type: octokit
    method: issues.update
    owner: "%payload.repository.owner.login%"
    repo: "%payload.repository.name%"
    issue_number: 1
steps:
  - title: Lektion 1 - Hello World
    description: Introduktion till kursen
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: module-0/module-0-lesson-1-done.md
        issue: 1
